b2atech/dhanman-myhome

src/Core/Dhanman.MyHome.Application.Contracts/Residents/ResidentListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Residents/ResidentNameListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Residents/ResidentNameResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Residents/ResidentResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Features/Residents/Queries/GetAllResidentNamesQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Residents/Queries/GetAllResidentNamesQueryHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Residents/Queries/GetAllResidentsQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Residents/Queries/GetAllResidentsQueryHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/Apartments/Resident.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240328142934_resident.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240328142934_resident.cs

get all resident

---

src/Core/Dhanman.MyHome.Application.Contracts/Residents/ResidentNameResponse.cs

get resident names

---

src/Core/Dhanman.MyHome.Domain/Entities/Apartments/Resident.cs
src/Core/Dhanman.MyHome.Domain/Entities/Apartments/ResidentRequest.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/ResidentConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/ResidentRequestConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Dhanman.MyHome.Persistence.csproj
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240401115546_residentrequest.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240401115546_residentrequest.cs

refactor: entity resident and residentrequest

refactor: entity resident and residentrequest

---

src/Core/Dhanman.MyHome.Application.Contracts/Common/EntityCreatedResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/ResidentRequests/CreateResidentRequestRequest.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/ResidentRequests/Commands/CreateResidentRequest/CreateResidentRequestCommand.cs
src/Core/Dhanman.MyHome.Application/Features/ResidentRequests/Commands/CreateResidentRequest/CreateResidentRequestCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/ResidentRequests/Events/ResidentRequestCreatedEvent.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IResidentRequestRepository.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DependencyInjection.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/ResidentRequestRepository.cs

feat: create endpoint for resident request

feat: create endpoint for resident request

---

src/Core/Dhanman.MyHome.Application.Contracts/ResidentRequests/ResidentRequestListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/ResidentRequests/ResidentRequestResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/ResidentRequests/Queries/GetAllResidentRequestsQuery.cs
src/Core/Dhanman.MyHome.Application/Features/ResidentRequests/Queries/GetAllResidentRequestsQueryHandler.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs

feat: get all resident request

feat: get all resident request

---

src/Core/Dhanman.MyHome.Application.Contracts/Apartments/ApartmentListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Apartments/ApartmentResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Features/Apartments/GetAllApartmentsQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Apartments/GetAllApartmentsQueryHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs

Created apartment get all endpoint

feat: added getall apartments

---

src/Core/Dhanman.MyHome.Application.Contracts/Residents/CreateResidentRequest.cs
src/Core/Dhanman.MyHome.Application/Features/Residents/Commands/CreateResident/CreateResidentCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Residents/Commands/CreateResident/CreateResidentCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Residents/Events/ResidentCreatedEvent.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IResidentRepository.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DependencyInjection.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/ResidentRepository.cs

feat: create endpoint for resident

feat: create endpoint for resident

---

src/Core/Dhanman.MyHome.Application.Contracts/Common/EntityCreatedResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Units/CreateUnitListRequest.cs
src/Core/Dhanman.MyHome.Application.Contracts/Units/CreateUnitRequest.cs
src/Core/Dhanman.MyHome.Application/Behaviors/UnitOfWorkBehaviour.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateUnit/CreateUnitCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateUnit/CreateUnitCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateUnit/CreateUnitCommandValidator.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Event/UnitCreatedEvent.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IOccupancyTypeRepository.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IOccupantTypeRepository.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IUnitRepository.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IUnitTypeRepository.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DependencyInjection.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/OccupancyTypeRepository.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/OccupantTypeRepository.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/UnitRepository.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/UnitTypeRepository.cs

feat: Import Units

---

src/Core/Dhanman.MyHome.Application.Contracts/Units/CreateUnitRequest.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateUnit/CreateUnitCommandHandler.cs

feat: error handled

---

src/Core/Dhanman.MyHome.Application/Constants/ResidentRequestStatus.cs
src/Core/Dhanman.MyHome.Application/Features/ResidentRequests/Commands/UpdateRequestApproveStatus/UpdateRequestApproveStatusCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/ResidentRequests/Commands/UpdateRequestRejectStatus/UpdateRequestRejectStatusCommandHandler.cs

constant included

---

src/Core/Dhanman.MyHome.Domain/Entities/Addresses/Address.cs
src/Core/Dhanman.MyHome.Domain/Entities/Addresses/AddressLine.cs
src/Core/Dhanman.MyHome.Domain/Entities/Addresses/CityId.cs
src/Core/Dhanman.MyHome.Domain/Entities/Banks/Bank.cs
src/Core/Dhanman.MyHome.Domain/Entities/Cities/City.cs
src/Core/Dhanman.MyHome.Domain/Entities/Countries/Country.cs
src/Core/Dhanman.MyHome.Domain/Entities/States/State.cs
src/Core/Dhanman.MyHome.Domain/Errors.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/AddressConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/BankConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/CityConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/CountryConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/StateConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Constants/TableNames.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240411091938_address.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240411091938_address.cs

add entities address, bank, city, state, country

feat: add entities address, bank, city, state, country

---

src/Core/Dhanman.MyHome.Application.Contracts/OccupancyTypes/OccupancyTypeListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/OccupancyTypes/OccupancyTypeResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/OccupancyTypes/Queries/GetAllOccupancyTypesQuery.cs
src/Core/Dhanman.MyHome.Application/Features/OccupancyTypes/Queries/GetAllOccupancyTypesQueryHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs

feat: get all occupancy types

---

src/Core/Dhanman.MyHome.Application.Contracts/Units/UnitResponse.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Queries/GetAllUnitsQueryHandler.cs

refactor: get all units - area and bhktype added

---

src/Core/Dhanman.MyHome.Application.Contracts/Visitors/VisitorListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Visitors/VisitorNameListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Visitors/VisitorNameResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Visitors/VisitorResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Queries/GetAllVisitorNamesQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Queries/GetAllVisitorNamesQueryHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Queries/GetAllVisitorsQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Queries/GetAllVisitorsQueryHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs

feat: get all visitors endpoint

---

src/Core/Dhanman.MyHome.Application.Contracts/Units/UnitDetailListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Units/UnitDetailResponse.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Queries/GetAllUnitDetailsQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Queries/GetAllUnitDetailsQueryHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/Apartments/Unit.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/UnitConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240425063045_unit2.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240425063045_unit2.cs

feat: get all unit details
Two issues 1) more than 7 parameter and in migration interger many times

feat: get all unit details

---

src/Core/Dhanman.MyHome.Application.Contracts/Units/UnitDetailResponse.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Queries/GetAllUnitDetailsQueryHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/Apartments/Unit.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/UnitConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240501085050_units.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240501085050_units.cs

refactor: add column in unit and refactor get all unit details

---

src/Core/Dhanman.MyHome.Application.Contracts/Units/UnitDetailResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Units/UnitResponse.cs
src/Core/Dhanman.MyHome.Domain/Entities/Apartments/Unit.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240507113236_unit-type.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240507113236_unit-type.cs

refactor type of bhk_type and area

---

src/Core/Dhanman.MyHome.Application.Contracts/Events/EventListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Events/EventResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/Events/Queries/GetAllEventsQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Events/Queries/GetAllEventsQueryHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/BookingFacilites/BookingFacilitie.cs
src/Core/Dhanman.MyHome.Domain/Entities/EventStatuses/EventStatus.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/EventsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/EventStatusConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Constants/TableNames.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240509064114_EventStatus.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240509064114_EventStatus.cs

get all events endpoint

---

src/Core/Dhanman.MyHome.Application.Contracts/BookingFacilites/BookingFacilitesListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/BookingFacilites/BookingFacilitesResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/BookingFacilities/Queries/GetAllBookingFacilitesQuery.cs
src/Core/Dhanman.MyHome.Application/Features/BookingFacilities/Queries/GetAllBookingFacilitesQueryHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Events/Queries/GetAllEventsQuery.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IBookingFacilitesRepository.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/EventsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DependencyInjection.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/BookingFacilitesRepository.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/UnitRepository.cs

create getAllBookingFacilities endpoint #55

create getAllBookingFacilities endpoint

---

src/Core/Dhanman.MyHome.Application.Contracts/ServiceProviderSubTypes/ServiceProivderSubTypeListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/ServiceProviderSubTypes/ServiceProivderSubTypeResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Units/GetUnitDetailRequest.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/ServiceProviderSubType/Queries/GetAllServiceProviderSubTypeQuery.cs
src/Core/Dhanman.MyHome.Application/Features/ServiceProviderSubType/Queries/GetAllServiceProviderSubTypeQueryHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/ServiceProviderSubTypes/ServiveProviderSubType.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ServiceProviderController.cs
src/Dhanman.MyHome.Api/Controllers/UnitsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/ServiceProviderSubTypeConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Constants/TableNames.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240509105910_ServiceProviderSubType.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240509105910_ServiceProviderSubType.cs

created getAllServiceProviderSubType #57

created getAllServiceProviderSubType

---

src/Core/Dhanman.MyHome.Application.Contracts/Events/CreateEventRequest.cs
src/Core/Dhanman.MyHome.Application/Features/Events/Commands/CreateEvent/CreateEventCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Events/Commands/CreateEvent/CreateEventCommandHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/Events/Event.cs
src/Dhanman.MyHome.Api/Controllers/EventsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/EventsConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240510065229_NewEvent.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240510065229_NewEvent.cs

bookingFacilitiesId in post Event

add bookingFacilitiesId in post Event

---

src/Core/Dhanman.MyHome.Application.Contracts/ServiceProviders/Address.cs
src/Core/Dhanman.MyHome.Application.Contracts/ServiceProviders/CreateServiceProviderRequest.cs
src/Core/Dhanman.MyHome.Application/Features/ServiceProviders/Commands/CreateServiceProvider/CreateServiceProviderCommand.cs
src/Core/Dhanman.MyHome.Application/Features/ServiceProviders/Commands/CreateServiceProvider/CreateServiceProviderCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/ServiceProviders/Events/ServiceProviderCreatedEvent.cs
src/Core/Dhanman.MyHome.Application/Features/ServiceProviders/Queries/GetAllServiceProvidersQueryHandler.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IAddressRepository.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IServiceProviderRepository.cs
src/Core/Dhanman.MyHome.Domain/Entities/ServiceProviders/ServiceProvider.cs
src/Dhanman.MyHome.Api/Controllers/ServiceProvidersController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/ServiceProviderConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DependencyInjection.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/AddressRepository.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/ServiceProviderRepository.cs

Two issues = **more parameters**

feat: endpoint create service provider

---

src/Core/Dhanman.MyHome.Application.Contracts/UnitServiceProviders/CreateUnitServiceProviderRequest.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/UnitServiceProviders/Commands/CreateUnitServiceProvider/CreateUnitServiceProviderCommand.cs
src/Core/Dhanman.MyHome.Application/Features/UnitServiceProviders/Commands/CreateUnitServiceProvider/UnitServiceProviderCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/UnitServiceProviders/Events/UnitServiceProviderCreatedEvent.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IUnitServiceProviderRespository.cs
src/Core/Dhanman.MyHome.Domain/Entities/UnitServiceProviders/ServiceProviderId.cs
src/Core/Dhanman.MyHome.Domain/Entities/UnitServiceProviders/UnitId.cs
src/Core/Dhanman.MyHome.Domain/Entities/UnitServiceProviders/UnitServiceProvider.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ServiceProvidersController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/UnitServicerProviderConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Constants/TableNames.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DependencyInjection.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240512122825_UnitServiceProvider.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240512122825_UnitServiceProvider.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/UnitServiceProviderRespository.cs

create post unit service provider endpoint

create post unit service provider endpoint

---

src/Core/Dhanman.MyHome.Application.Contracts/ServiceProviderTypes/ServiceProivderTypeListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/ServiceProviderTypes/ServiceProivderTypeResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Features/ServiceProviderTypes/Queries/GetAllServiceProviderTypeQuery.cs
src/Core/Dhanman.MyHome.Application/Features/ServiceProviderTypes/Queries/GetAllServiceProviderTypeQueryHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ServiceProvidersController.cs

create get all service provider type endpoint

create get all service provider type endpoint

---

src/Core/Dhanman.MyHome.Domain/Entities/Events/Event.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/EventsConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240514062555_event.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240514062555_event.cs

add column to event table

---

src/Core/Dhanman.MyHome.Application.Contracts/ServiceProviders/CreateServiceProviderRequest.cs
src/Core/Dhanman.MyHome.Application/Features/ServiceProviders/Commands/CreateServiceProvider/CreateServiceProviderCommand.cs
src/Core/Dhanman.MyHome.Application/Features/ServiceProviders/Commands/CreateServiceProvider/CreateServiceProviderCommandHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/ServiceProviders/ServiceProvider.cs
src/Dhanman.MyHome.Api/Controllers/ServiceProvidersController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240514131947_refactorServiceProviderEndpoint.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240514131947_refactorServiceProviderEndpoint.cs

refactor service provider endpoint

refactor service provider endpoint

---

src/Core/Dhanman.MyHome.Application.Contracts/ResidentRequests/CreateResidentRequestRequest.cs
src/Core/Dhanman.MyHome.Application/Features/ResidentRequests/Commands/CreateResidentRequest/CreateResidentRequestCommand.cs
src/Core/Dhanman.MyHome.Application/Features/ResidentRequests/Commands/CreateResidentRequest/CreateResidentRequestCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Queries/GetAllUnitNamesQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Queries/GetAllUnitNamesQueryHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ResidentsController.cs
src/Dhanman.MyHome.Api/Controllers/UnitsController.cs

refactor : create resident request and get all unit names endpoints

refactor : create resident request and get all unit names endpoints

---

src/Core/Dhanman.MyHome.Application/Features/Complaints/Commands/CreateComplaint/CreateComplaintCommand.cs
src/Dhanman.MyHome.Api/Controllers/ComplaintsController.cs

refactor : add description and docLink in request

refactor : add description and docLink in request

---

src/Core/Dhanman.MyHome.Application.Contracts/Catergories/CategoryListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Catergories/CategoryResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/SubCategories/SubCategoryListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/SubCategories/SubCategoryResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/Categories/Queries/GetAllCategoryQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Categories/Queries/GetAllCategoryQueryHandler.cs
src/Core/Dhanman.MyHome.Application/Features/SubCategories/GetAllSubCategoryQuery.cs
src/Core/Dhanman.MyHome.Application/Features/SubCategories/GetAllSubCategoryQueryHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/Categories/Category .cs
src/Core/Dhanman.MyHome.Domain/Entities/SubCategories/SubCategory .cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/CategoriesController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/CategoryConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/SubCategoryConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Constants/TableNames.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240520071030_CategoryAndSubCategory.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240520071030_CategoryAndSubCategory.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240520071802_UpdateCategoryAndSubCategoryHD.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240520071802_UpdateCategoryAndSubCategoryHD.cs

creat getAll catergory and sub category endpoints

feat: creat getAll catergory and sub category endpoints

---

src/Core/Dhanman.MyHome.Application.Contracts/UnitServiceProviders/AssignSPUnitsListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/UnitServiceProviders/AssignSPUnitsResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/UnitServiceProviders/GetAssignUnitsResquest.cs
src/Core/Dhanman.MyHome.Application/Features/UnitServiceProviders/Commands/GetAssignUnits/GetAssignUnitsCommand.cs
src/Core/Dhanman.MyHome.Application/Features/UnitServiceProviders/Commands/GetAssignUnits/GetAssignUnitsCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/UnitServiceProviders/Events/GetAssignUnitsCreatedEvent.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/GetUnitDetails/GetUnitDetailsCommand.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ServiceProvidersController.cs
src/Dhanman.MyHome.Api/Controllers/UnitsController.cs

create get all assign units endpoint #84

feat: create get all assign units endpoint

---

src/Core/Dhanman.MyHome.Application.Contracts/Dhanman.MyHome.Application.Contracts.csproj
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Domain/Dhanman.MyHome.Domain.csproj
src/Dhanman.MyHome.Api/Dhanman.MyHome.Api.csproj
src/Dhanman.MyHome.Api/Program.cs
src/Infrastructure/Dhanman.Infrastructure.Authentication/Dhanman.Infrastructure.Authentication.csproj
src/Infrastructure/Dhanman.MyHome.Persistence/Dhanman.MyHome.Persistence.csproj
test/integration/Dhanman.MyHome.Database.Integration.Tests/Dhanman.MyHome.Database.Integration.Tests.csproj
test/integration/Dhanman.MyHome.Integration.Tests/Dhanman.MyHome.Api.Integration.Tests.csproj
test/unit/Dhanman.MyHome.Api.Tests/Dhanman.MyHome.Api.Tests.csproj
test/unit/Dhanman.MyHome.Domain.Tests/Dhanman.MyHome.Domain.Tests.csproj

feat: update packages

---

src/Core/Dhanman.MyHome.Application.Contracts/Buildings/CreateBuildingRequest.cs
src/Core/Dhanman.MyHome.Application/Features/Buildings/Commands/CreateBuilding/CreateBuildingCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Buildings/Commands/CreateBuilding/CreateBuildingCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Buildings/Commands/CreateBuilding/CreateBuildingCommandValidator.cs
src/Core/Dhanman.MyHome.Application/Features/Buildings/Events/BuildingCreatedEvent.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IBuildingRepository.cs
src/Core/Dhanman.MyHome.Domain/Entities/Buildings/Building.cs
src/Dhanman.MyHome.Api/Controllers/BuildingsController.cs
src/Dhanman.MyHome.Api/Controllers/CategoriesController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DependencyInjection.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/BuildingRepository.cs

feat: save building endpoint

---

src/Core/Dhanman.MyHome.Application.Contracts/Buildings/CreateBuildingRequest.cs

refactor: remove audible property

---

src/Core/Dhanman.MyHome.Application.Contracts/BuildingTypes/BuildingTypeListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/BuildingTypes/BuildingTypeResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Features/BuildingTypes/Queries/GetAllBuildingTypesQuery.cs
src/Core/Dhanman.MyHome.Application/Features/BuildingTypes/Queries/GetAllBuildingTypesQueryHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs

feat: get All buildingTypesendpoint

---

src/Core/Dhanman.MyHome.Domain/Dhanman.MyHome.Domain.csproj

remove .TMP from from CSproj file for loading project

feat: remove .TMP from from CSproj file for loading project

---

src/Core/Dhanman.MyHome.Application.Contracts/Buildings/CreateBuildingRequest.cs
src/Core/Dhanman.MyHome.Application.Contracts/Floors/CreateFloorRequest.cs
src/Core/Dhanman.MyHome.Application.Contracts/Floors/FloorResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Gates/CreateGateRequest.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/Buildings/Commands/CreateBuilding/CreateBuildingCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Commands/CreateFloor/CreateFloorCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Commands/CreateFloor/CreateFloorCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Commands/CreateFloor/CreateFloorCommandValidator.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Events/FloorCreatedEvent.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Queries/GetAllFloorsQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Queries/GetAllFloorsQueryHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Commands/CreateGate/CreateGateCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Commands/CreateGate/CreateGateCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Commands/CreateGate/CreateGateCommandValidator.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Events/GateCreatedEvent.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Events/GateDeletedEvent.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Events/GateUpdatedEvent.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Queries/GetAllGateNamesQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Queries/GetAllGatesQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Queries/GetAllGatesQueryHandler.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IFloorRepository.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IGateRepository.cs
src/Core/Dhanman.MyHome.Domain/Entities/Floors/Floor.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs
src/Dhanman.MyHome.Api/Controllers/BuildingsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DependencyInjection.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/FloorRepository.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/GateRepository.cs

post and get api for floor & gate

Feature/mh 96 post and get api for floor & gate

---

src/Core/Dhanman.MyHome.Application.Contracts/Residents/CreateResidentRequest.cs
src/Core/Dhanman.MyHome.Application/Features/ResidentRequests/Commands/UpdateRequestApproveStatus/UpdateRequestApproveStatusCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Residents/Commands/CreateResident/CreateResidentCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Residents/Commands/CreateResident/CreateResidentCommandHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/Residents/Resident.cs
src/Dhanman.MyHome.Api/Controllers/ResidentsController.cs

refactor: create resident endpoint

---

src/Core/Dhanman.MyHome.Application.Contracts/Units/CreateUnitRequest.cs
src/Core/Dhanman.MyHome.Application.Contracts/Units/CreateUnitsListRequest.cs
src/Core/Dhanman.MyHome.Application.Contracts/Units/CreateUnitsRequest.cs
src/Core/Dhanman.MyHome.Application.Contracts/Units/UnitResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Units/UpdateUnitRequest.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateUnit/CreateUnitCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateUnits/CreateUnitsCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateUnits/CreateUnitsCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/DeleteUnit/DeleteUnitCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/DeleteUnit/DeleteUnitsCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/UpdateUnit/UpdateUnitCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/UpdateUnit/UpdateUnitCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Event/UnitUpdateEvent.cs
src/Core/Dhanman.MyHome.Domain/Entities/Units/Unit.cs
src/Core/Dhanman.MyHome.Domain/Exceptions/InvoiceNotFoundException.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs
src/Dhanman.MyHome.Api/Controllers/UnitsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/UnitConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240529033637_updateUnit.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240529033637_updateUnit.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/ApplicationDbContextModelSnapshot.cs

reate save, edit and delete unit api

Feat: create save, edit and delete unit api

---

src/Core/Dhanman.MyHome.Application.Contracts/Floors/FloorResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Floors/UpdateFloorRequest.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/Floors/Commands/DeleteFloor/DeleteFloorCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Commands/DeleteFloor/DeleteFloorCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Commands/UpdateFloor/UpdateFloorCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Commands/UpdateFloor/UpdateFloorCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Commands/UpdateFloor/UpdateFloorCommandValidator.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Events/FloorUpdatedEvent.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Queries/GetAllFloorNamesQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Queries/GetAllFloorsQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Floors/Queries/GetAllFloorsQueryHandler.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IFloorRepository.cs
src/Core/Dhanman.MyHome.Domain/Entities/Floors/Floor.cs
src/Core/Dhanman.MyHome.Domain/Entities/Gates/Gate.cs
src/Core/Dhanman.MyHome.Domain/Exceptions/FloorNotFoundException.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/FloorRepository.cs

edit and delete api for floor & gate

Feature/mh 96 edit and delete api for floor & gate

---

src/Core/Dhanman.MyHome.Application.Contracts/Gates/UpdateGateRequest.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/Gates/Commands/DeleteGate/DeleteGateCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Commands/DeleteGate/DeleteGateCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Commands/DeleteGate/DeleteGateCommandValidator.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Commands/UpdateGate/UpdateGateCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Commands/UpdateGate/UpdateGateCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Gates/Commands/UpdateGate/UpdateGateCommandValidator.cs
src/Core/Dhanman.MyHome.Domain/Entities/Units/Unit.cs
src/Core/Dhanman.MyHome.Domain/Exceptions/GateNotFoundException.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs

create delete and update gate endpoint

feat: create delete and update gate endpoint

---

src/Core/Dhanman.MyHome.Application.Contracts/UnitServiceProviders/CreateUnitServiceProviderRequest.cs
src/Core/Dhanman.MyHome.Application.Contracts/Units/UnitResponse.cs
src/Core/Dhanman.MyHome.Application/Features/UnitServiceProviders/Commands/CreateUnitServiceProvider/CreateUnitServiceProviderCommand.cs
src/Core/Dhanman.MyHome.Application/Features/UnitServiceProviders/Commands/CreateUnitServiceProvider/UnitServiceProviderCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/UnitServiceProviders/Events/UnitServiceProviderCreatedEvent.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Queries/GetAllUnitsQueryHandler.cs
src/Dhanman.MyHome.Api/Controllers/ServiceProvidersController.cs

post service provider endpoint

chore: post service provider endpoint

---

src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateUnit/CreateUnitCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateUnits/CreateUnitsCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateUnits/CreateUnitsCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Event/UnitCreatedEvent.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IUnitRepository.cs
src/Dhanman.MyHome.Api/Controllers/UnitsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/UnitRepository.cs

fix: create api of unit

---

src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/FloorRepository.cs

chore: add ignoreFiltere

---

src/Core/Dhanman.MyHome.Application/Features/ResidentRequests/Commands/CreateResidentRequest/CreateResidentRequestCommandHandler.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/ResidentRequestConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240604082937_residentrequest1.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240604082937_residentrequest1.cs

fix: addressid null issue

---

src/Core/Dhanman.MyHome.Application.Contracts/Visitors/CreateVisitorRequest.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Commands/CreateVisitor/CreateVisitorCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Commands/CreateVisitor/CreateVisitorCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Commands/CreateVisitor/CreateVisitorCommandValidator.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Commands/DeleteVisitor/DeleteVisitorCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Commands/DeleteVisitor/DeleteVisitorCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Commands/DeleteVisitor/DeleteVisitorCommandValidator.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Events/VisitorCreatedEvent.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Events/VisitorDeletedEvent.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Events/VisitorUpdatedEvent.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/IVisitorRepository.cs
src/Core/Dhanman.MyHome.Domain/Entities/Visitors/Visitor.cs
src/Core/Dhanman.MyHome.Domain/Exceptions/VisitorNotFoundException.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/VisitorsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DependencyInjection.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/VisitorRepository.cs

feat: add & delete endpoint

---

src/Core/Dhanman.MyHome.Application.Contracts/UnitServiceProviders/AssignUnitListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/UnitServiceProviders/ServiceProviderAssignedUnitResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/UnitServiceProviders/Queries/GetAllServiceProviderUnitsByIdQuery.cs
src/Core/Dhanman.MyHome.Application/Features/UnitServiceProviders/Queries/GetAllServiceProviderUnitsByIdQueryHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ServiceProvidersController.cs
src/Dhanman.MyHome.Api/Controllers/UnitsController.cs

getAllServiceProviderUnits endpoint

create getAllServiceProviderUnits endpoint

---

src/Core/Dhanman.MyHome.Application.Contracts/Units/GetUnitsByFloorIdRequest.cs
src/Core/Dhanman.MyHome.Application.Contracts/Units/UnitByFloorIdListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Units/UnitByFloorIdResponse.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/GetUnitDetails/GetUnitByFloorIdCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/GetUnitDetails/GetUnitByFloorIdCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Event/GetUnitByFloorIdEvent.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/UnitsController.cs

get all units by floor id endpoint

feat: get all units by building and  floor id endpoint

---

src/Core/Dhanman.MyHome.Application.Contracts/ServiceProviders/CreateServiceProviderRequest.cs
src/Core/Dhanman.MyHome.Application.Contracts/ServiceProviders/ValidateServiceProviderRequest.cs
src/Core/Dhanman.MyHome.Application/Features/ServiceProviders/Commands/CreateServiceProvider/CreateServiceProviderCommand.cs
src/Core/Dhanman.MyHome.Application/Features/ServiceProviders/Commands/CreateServiceProvider/CreateServiceProviderCommandHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/ServiceProviders/ServiceProvider.cs
src/Dhanman.MyHome.Api/Controllers/ServiceProvidersController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/ServiceProviderConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240628053807_refactorSP2.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240628053807_refactorSP2.cs

change table name and remove created by in the handler

fix: change table name and remove created by in the handler

---

src/Core/Dhanman.MyHome.Domain/Entities/DeliveryCompanies/DeliveryCompany.cs
src/Core/Dhanman.MyHome.Domain/Entities/DeliveryCompanyCategories/DeliveryCompanyCategory.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/DeliveryCompanyCategoryConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/DeliveryCompanyConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Constants/TableNames.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240628120141_delivery_companies_delivery_company_categories.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20240628120141_delivery_companies_delivery_company_categories.cs

**0 issue**   **Duplication in migration**

feat: create entity delivery companies and delivery company categories

---

src/Core/Dhanman.MyHome.Application.Contracts/DeliveryCompanies/DeliveryCompanyListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/DeliveryCompanies/DeliveryCompanyResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Features/DeliveryCompanies/Queries/GetAllDeliveryCompaniesQuery.cs
src/Core/Dhanman.MyHome.Application/Features/DeliveryCompanies/Queries/GetAllDeliveryCompaniesQueryHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/DeliveryCompaniesController.cs

feat: get delivery companies

---

src/Core/Dhanman.MyHome.Domain/Dhanman.MyHome.Domain.csproj
src/Dhanman.MyHome.Api/AuthorizationExtensions.cs
src/Dhanman.MyHome.Api/Dhanman.MyHome.Api.csproj
src/Infrastructure/Dhanman.MyHome.Persistence/Dhanman.MyHome.Persistence.csproj

dynamic permission and pakage update

refactor: dynamic permission and pakage update

---

src/Core/Dhanman.MyHome.Application/Abstractions/Data/IApplicationDbContext.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/ServiceProviderRepository.cs

https://localhost:7240/api/v1/serviceProviders
{
"firstName": "Jon",
"lastName": "Li",
"email": "jj@gmail.com",
"visitingFrom": "Sangli",
"contactNumber": "9822111111",
"permanentAddress": {
"countryId": "3649e6c0-fbaa-4f27-aef1-ef080b650b23",
"stateId": "00571074-280a-4196-903d-47c61a60734d",
"cityName": "Jaitpeer",
"addressLine1": "Happy Home,",
"addressLine2": "Colony road, Sangli",
"zipCode": "416416"
},
"presentAddress": {
"countryId": "3649e6c0-fbaa-4f27-aef1-ef080b650b23",
"stateId": "00571074-280a-4196-903d-47c61a60734d",
"cityName": "Jaitpeer",
"addressLine1": "Happy Home,",
"addressLine2": "Colony road, Sangli",
"zipCode": "416416"
},
"serviceProviderTypeId": 10,
"serviceProviderSubTypeId": 116,
"vehicleNumber": "",
"identityTypeId": 1,
"identityNumber": "1111",
"validityDate": …

refactor: create service provider by sp

---

src/Infrastructure/Dhanman.MyHome.Persistence/DependencyInjection.cs

feat: add repository in dependency injection

---

src/Core/Dhanman.MyHome.Application.Contracts/VisitorLogs/VisitorLogResponse.cs
src/Core/Dhanman.MyHome.Application/Features/VisitorLogs/Queries/GetAllVisitorLogsQueryHandler.cs

**unitId and unit names are added in get visitor log**

feat: refactor get visitor logs

---

src/Core/Dhanman.MyHome.Application.Contracts/Visitors/VisitorsByUnitIdListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Visitors/VisitorsByUnitIdResponse.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Queries/GetVisitorsByUnitIdQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Queries/GetVisitorsByUnitIdQueryHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/VisitorsController.cs

https://api-dhanman-myhome-nonprod.azurewebsites.net/api/v1/visitorsByUnitId/12fb50f0-9998-456f-8aee-bb83ab2fbbdb/67

feat: get visitors by unitId

---

src/Core/Dhanman.MyHome.Application.Contracts/Units/CreateUnitsRequest.cs
src/Core/Dhanman.MyHome.Application/Abstractions/ICommonServiceClient.cs
src/Core/Dhanman.MyHome.Application/Abstractions/ISalesServiceClient.cs
src/Core/Dhanman.MyHome.Application/Abstractions/ServiceClientBase.cs
src/Core/Dhanman.MyHome.Application/Caching/CacheService.cs
src/Core/Dhanman.MyHome.Application/Constants/ApiClientRoutes.cs
src/Core/Dhanman.MyHome.Application/Contracts/CustomerDto.cs
src/Core/Dhanman.MyHome.Application/DependencyInjection.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateUnits/CreateUnitsCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateUnits/CreateUnitsCommandHandler.cs
src/Core/Dhanman.MyHome.Application/ServiceClient/CommonServiceClient.cs
src/Core/Dhanman.MyHome.Application/ServiceClient/SalesServiceClient.cs
src/Core/Dhanman.MyHome.Domain/Entities/Units/Unit.cs
src/Dhanman.MyHome.Api/Controllers/UnitsController.cs
src/Dhanman.MyHome.Api/Dhanman.MyHome.Api.csproj
src/Dhanman.MyHome.Api/Middleware/ExceptionHandlerMiddleware.cs
src/Dhanman.MyHome.Api/Program.cs
src/Dhanman.MyHome.Api/appsettings.Development.json
src/Dhanman.MyHome.Api/appsettings.Production.json
src/Dhanman.MyHome.Api/appsettings.QA.json

refactor: create unit

---

src/Core/Dhanman.MyHome.Application/Features/Units/Queries/GetAllUnitsQueryHandler.cs

refactor: total units and number of units issue

---

src/Core/Dhanman.MyHome.Application.Contracts/Units/UnitRequest.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateMultipleUnits/CreateMultipleUnitCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateMultipleUnits/CreateMultipleUnitCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Command/CreateMultipleUnits/CreateMultipleUnitCommandValidator.cs

create insert mutiple endpoint

feat: create insert mutiple endpoint

---

src/Core/Dhanman.MyHome.Application.Contracts/Gates/GateTypeListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Gates/GateTypeResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Dhanman.MyHome.Application.csproj
src/Core/Dhanman.MyHome.Application/Features/GateTypes/Queries/GetAllGateTypeQuery.cs
src/Core/Dhanman.MyHome.Application/Features/GateTypes/Queries/GetAllGateTypeQueryHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/GatesController.cs

create get all gate types endpoint

feat: create get all gate types endpoint

---

src/Core/Dhanman.MyHome.Domain/Entities/VisitorStatuses/VisitorStatus.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/VisitorStatusConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Constants/TableNames.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250304064946_visitor_statuses.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250304064946_visitor_statuses.cs

feat: create entity visitor_statuses

---

src/Core/Dhanman.MyHome.Application.Contracts/TicketCatetories/TicketCatetoryListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/TicketCatetories/TicketCatetoryResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/TicketPriorities/TicketPriorityListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/TicketPriorities/TicketPriorityResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/TicketStatuses/TicketStatusListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/TicketStatuses/TicketStatusResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Features/Tickets/Queries/GetTicketCatetoriesQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Tickets/Queries/GetTicketCatetoriesQueryHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Tickets/Queries/GetTicketPrioritiesQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Tickets/Queries/GetTicketPrioritiesQueryHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Tickets/Queries/GetTicketStatusesQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Tickets/Queries/GetTicketStatusesQueryHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs
src/Dhanman.MyHome.Api/Controllers/TicketsController.cs

feat: get status, catetory and priority

---

src/Core/Dhanman.MyHome.Domain/Entities/Tickets/Ticket.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/TicketConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250305053820_tickets1.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250305053820_tickets1.cs

refactor: adding apartment_id column to tickets

---

src/Core/Dhanman.MyHome.Application.Contracts/Tickets/TicketListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Tickets/TicketResponse.cs
src/Core/Dhanman.MyHome.Application/Features/Tickets/Queries/GetAllTicketsQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Tickets/Queries/GetAllTicketsQueryHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/TicketsController.cs

https://localhost:7240/api/v1/tickets/12fb50f0-9998-456f-8aee-bb83ab2fbbdb

feat: get tickets

---

src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Features/Buildings/Queries/GetBuildingByIdQueryHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Tickets/Queries/GetTicketByIdQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Tickets/Queries/GetTicketByIdQueryHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/TicketsController.cs

feat: get ticket by id

---

src/Core/Dhanman.MyHome.Application.Contracts/Visitors/UpdateVisitorRequest.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Commands/UpdateVisitor/UpdateVisitorCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Commands/UpdateVisitor/UpdateVisitorCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Events/VisitorUpdatedEvent.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/VisitorsController.cs

Create visitor  **87**
Update visitor  **87**

feat: update visitor

---

src/Core/Dhanman.MyHome.Application.Contracts/Tickets/ServiceProviderTicketCategoryListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Tickets/ServiceProviderTicketCategoryResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Features/Tickets/Queries/GetAllServiceProviderTicketCategoryQuery.cs
src/Core/Dhanman.MyHome.Application/Features/Tickets/Queries/GetAllServiceProviderTicketCategoryQueryHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/ServiceProviderTicketCategories/ServiceProviderTicketCategory.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/TicketsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/ApplicationDbContext.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/ServiceProviderTicketCategoryConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Constants/TableNames.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250313084849_serviceProviderCategory.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250313084849_serviceProviderCategory.cs

create ticket service provider

feat: create ticket service provider

---

.vs/Dhanman.MyHome/config/applicationhost.config
src/Core/Dhanman.MyHome.Application.Contracts/Visitors/CreateVisitorRequest.cs
src/Core/Dhanman.MyHome.Application.Contracts/Visitors/VisitorsByUnitIdResponse.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Commands/CreateVisitor/CreateVisitorCommand.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Commands/CreateVisitor/CreateVisitorCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/Visitors/Queries/GetVisitorsByUnitIdQueryHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/Visitors/Visitor.cs
src/Dhanman.MyHome.Api/Controllers/VisitorsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/VisitorConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250319085711_refactorVisitors.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250319085711_refactorVisitors.cs

add entry time and exit time props in vistiors and refactoe the vistorsgetbyUnit is endpoint

refactor: add entry time and exit time props in vistiors

---

src/Core/Dhanman.MyHome.Application.Contracts/TicketServiceProviderOtps/CreateTicketServiceProviderOtpRequest.cs
src/Core/Dhanman.MyHome.Application.Contracts/TicketServiceProviderOtps/TicketServiceProviderOtpResponse.cs
src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Application/Features/TicketServiceProviderOtps/Command/CreateTicketServiceProviderOtpCommand.cs
src/Core/Dhanman.MyHome.Application/Features/TicketServiceProviderOtps/Command/CreateTicketServiceProviderOtpCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/TicketServiceProviderOtps/Event/TicketServiceProviderOtpCreatedEvent.cs
src/Core/Dhanman.MyHome.Application/Features/TicketServiceProviderOtps/Queries/GetOtpByTicketIdQuery.cs
src/Core/Dhanman.MyHome.Application/Features/TicketServiceProviderOtps/Queries/GetOtpByTicketIdQueryHandler.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/ITicketServiceProviderOtpRepository.cs
src/Core/Dhanman.MyHome.Domain/Entities/TicketServiceProviderOtps/TicketServiceProviderOtp.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/TicketsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/TicketServiceProviderOtpConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Constants/TableNames.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DependencyInjection.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250321063201_TicketServiceProviderOtps.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250321063201_TicketServiceProviderOtps.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/TicketServiceProviderOtpRepository.cs

feat: ticket otp

---

src/Core/Dhanman.MyHome.Application.Contracts/Units/UnitResponse.cs
src/Core/Dhanman.MyHome.Application/Features/Units/Queries/GetUnitByIdQueryHandler.cs

add customer name and contact number

fix: add customer name and contact number

---

src/Core/Dhanman.MyHome.Application/Constants/CacheKeys.cs
src/Core/Dhanman.MyHome.Domain/Abstractions/ICommunityResidentRequestRepository.cs
src/Core/Dhanman.MyHome.Domain/Entities/CommunityResidentRequests/CommunityResidentRequest.cs
src/Dhanman.MyHome.Api/Controllers/ResidentsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/CommunityResidentRequestConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Constants/TableNames.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DependencyInjection.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250325105516_community_resident_requests.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250325105516_community_resident_requests.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Repositories/CommunityResidentRequestRepository.cs

feat: create entity and repository community resident requests

---

src/Core/Dhanman.MyHome.Application.Contracts/CommunityResidentRequests/CreateCommunityResidentRequestRequest.cs
src/Core/Dhanman.MyHome.Application/Features/CommunityResidentRequests/Commands/CreateCommunityResidentRequest/CreateCommunityResidentRequestCommand.cs
src/Core/Dhanman.MyHome.Application/Features/CommunityResidentRequests/Commands/CreateCommunityResidentRequest/CreateCommunityResidentRequestCommandHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/CommunityResidentRequests/CommunityResidentRequest.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ResidentsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/CommunityResidentRequestConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250325124719_community-resi-req.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250325124719_community-resi-req.cs

**v1/community-resident-request**
{
"memberType": "Normal",
"userName": "Saravanan",
"password": "Saravanan123",
"firstName": "S",
"lastName": "Saravanan",
"hattyId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"email": "ss@gmail.com",
"mobileNumber": "9822114422",
"companyName": "Test",
"designation": "Manager",
"currentAddress": {
"countryId": "3649e6c0-fbaa-4f27-aef1-ef080b650b23",
"stateId": "00571074-280a-4196-903d-47c61a60734d",
"cityId": "9d55cb34-1126-47a4-a3b8-81c37e61aa63",
"cityName": "Banglore",
"addressLine1": "L1",
"addressLine2": "L2",
"zipCode": "560076"
},
"dateOfBirth": "2025-03-25T13:02:39.719Z",
"gender": "M",
"maritalStatus": "Married",
"aboutYourSelf": "I am Saravanan",
"spouseName": "Saravanani",
"spouseHattyId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}

feat: create community resident request

---

src/Core/Dhanman.MyHome.Domain/Entities/CommunityUserDetails/CommunityUserDetail.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/CommunityUserDetailConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Constants/TableNames.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250325122947_communityUserDetailTable.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250325122947_communityUserDetailTable.cs

feat: create cmmunity member detail

---

src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/ApartmentsController.cs
src/Dhanman.MyHome.Api/Controllers/PublicController.cs
src/Dhanman.MyHome.Api/Controllers/ResidentsController.cs
src/Dhanman.MyHome.Api/Infrastructure/PublicApiController.cs

refactor: add public controller

---

src/Core/Dhanman.MyHome.Application.Contracts/MemberRequests/CreateMemberRequestRequest.cs
src/Core/Dhanman.MyHome.Application/Features/MemberRequests/Commands/CreateMemberRequest/CreateMemberRequestCommand.cs
src/Core/Dhanman.MyHome.Application/Features/MemberRequests/Commands/CreateMemberRequest/CreateMemberRequestCommandHandler.cs
src/Core/Dhanman.MyHome.Application/Features/MemberRequests/Events/MemberRequestCreatedEvent.cs
src/Core/Dhanman.MyHome.Domain/Entities/ResidentRequests/ResidentRequest.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/PublicController.cs
src/Dhanman.MyHome.Api/Infrastructure/PublicApiController.cs

**b0a926d5-acf5-4f7d-ab68-fc59948aad84**
{  
"firstName": "S",
"lastName": "Saravanan",
"email": "ss@gmail.com",
"mobileNumber": "9822114422",
"memberAdditionalDetails": {
"memberType": "Normal",
"userName": "Saravanan",
"password": "Saravanan123",
"hattyId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"companyName": "Test",
"designation": "Manager",
"dateOfBirth": "2025-03-26T13:30:02.802Z",
"gender": "M",
"maritalStatus": "Married",
"aboutYourSelf": "I am Saravanan",
"spouseName": "Saravanani",
"spouseHattyId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
},
"currentAddress": {
"countryId": "3649e6c0-fbaa-4f27-aef1-ef080b650b23",
"stateId": "00571074-280a-4196-903d-47c61a60734d",
"cityId": "9d55cb34-1126-47a4-a3b8-81c37e61aa63",
"cityName": "Banglore",
"addressLine1": "L1",
"addressLine2": "L2", …

refactor: create member request

---

src/Core/Dhanman.MyHome.Application.Contracts/MemberRequests/MemberRequestListResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/MemberRequests/MemberRequestResponse.cs
src/Core/Dhanman.MyHome.Application/Features/MemberRequests/Queries/GetAllMemberRequestsQuery.cs
src/Core/Dhanman.MyHome.Application/Features/MemberRequests/Queries/GetAllMemberRequestsQueryHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/CommunityResidentRequests/CommunityResidentRequest.cs
src/Core/Dhanman.MyHome.Domain/Entities/ResidentRequests/ResidentRequest.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/PublicController.cs
src/Dhanman.MyHome.Api/Controllers/ResidentsController.cs

feat: get member request

---

src/Core/Dhanman.MyHome.Application/Features/MemberRequests/Commands/UpdateMemberApproveStatus/UpdateMemberApproveStatusCommandHandler.cs

https://docs.google.com/document/d/1ahmA6IEsjIkWl__W8LuwcN1MBTyCFJZMlEYF4ljVcF0/edit?tab=t.0
Userid 
{23b9fa52-1242-4849-8dda-92b7449a9d2e}

feat: approve member request

---

src/Core/Dhanman.MyHome.Application.Contracts/Common/EntityUpdatedResponse.cs
src/Core/Dhanman.MyHome.Application.Contracts/Visitors/UpdateVisitorLogRequest.cs
src/Core/Dhanman.MyHome.Application/Features/VisitorLogs/Commands/UpdateVisiotLog/UpdateVisitorLogCommand.cs
src/Core/Dhanman.MyHome.Application/Features/VisitorLogs/Commands/UpdateVisiotLog/UpdateVisitorLogCommandHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/VisitorsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DBObjects/Functions/ApprovalVisitor.sql
src/Infrastructure/Dhanman.MyHome.Persistence/DBObjects/Functions/RejectVisitor.sql
src/Infrastructure/Dhanman.MyHome.Persistence/DBObjects/Functions/checkOut.sql

**Refactor:** The logic of the check out multiple.

refactor: the logic of the check out multiple

---

src/Core/Dhanman.MyHome.Application.Contracts/VisitorApprovals/CreateVisitorApprovalRequest.cs
src/Core/Dhanman.MyHome.Application/Features/VisitorApprovals/Commands/CreateVisitorApproval/CreateVisitorApprovalCommand.cs
src/Core/Dhanman.MyHome.Application/Features/VisitorApprovals/Commands/CreateVisitorApproval/CreateVisitorApprovalCommandHandler.cs
src/Core/Dhanman.MyHome.Domain/Entities/VisitorApprovals/VisitorApproval.cs
src/Core/Dhanman.MyHome.Domain/Entities/VisitorVehicles/VisitorVehicles.cs
src/Dhanman.MyHome.Api/Controllers/VisitorsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/VisitorApprovalConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Configurations/VisitorVehiclesConfiguration.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Constants/TableNames.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DBObjects/Functions/saveVisitorApproval.sql
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250409092647_VisitorVehiclesCreate.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250409092647_VisitorVehiclesCreate.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250409104427_RefcatorVisitorApproval.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250409104427_RefcatorVisitorApproval.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250409122350_RefcatorVisitorVehicles.Designer.cs
src/Infrastructure/Dhanman.MyHome.Persistence/Migrations/Application/20250409122350_RefcatorVisitorVehicles.cs

**Refactor:** _Visitor handler and visitor vehicles_

Refactor visitor handler and visitor vehicles

---

src/Core/Dhanman.MyHome.Application.Contracts/VisitorApprovals/UpadateVisitorApproveRequest.cs
src/Core/Dhanman.MyHome.Application/Features/VisitorApprovals/Commands/UpdateVisitorApproval/UpdateVisitorApproveCommand.cs
src/Core/Dhanman.MyHome.Application/Features/VisitorApprovals/Commands/UpdateVisitorApproval/UpdateVisitorApproveCommandHandler.cs
src/Dhanman.MyHome.Api/Contracts/ApiRoutes.cs
src/Dhanman.MyHome.Api/Controllers/VisitorsController.cs
src/Infrastructure/Dhanman.MyHome.Persistence/DBObjects/Functions/update_visitor_approval.sql

**Feat:** update visitor approve

Feat update visitor approve
